"""Events this module emits (see ARCHITECTURE.md §5)."""

from app.shared.events import TOPIC_BOOKMARKED, TRENDING_COLD_NICHE_REQUESTED, TRENDING_REFRESHED

__all__ = ["TRENDING_REFRESHED", "TOPIC_BOOKMARKED", "TRENDING_COLD_NICHE_REQUESTED"]
