"""unique constraints for analytics_daily and usage

Revision ID: 24122350e4a3
Revises: 5ed3c7969088
Create Date: 2026-07-18 03:39:04.406734

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '24122350e4a3'
down_revision: str | None = '5ed3c7969088'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_analytics_daily_channel_day', 'analytics_daily', ['channel_id', 'day'])
    op.create_unique_constraint('uq_usage_user_day', 'usage', ['user_id', 'day'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usage_user_day', 'usage', type_='unique')
    op.drop_constraint('uq_analytics_daily_channel_day', 'analytics_daily', type_='unique')
    # ### end Alembic commands ###
