"""technical design gap closure: schema fields, feature flags, refinement, auto-match

Revision ID: 2af37296507c
Revises: 844e11f1dd7b
Create Date: 2026-07-18 18:08:59.415140

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2af37296507c'
down_revision: str | None = '844e11f1dd7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=True)
    op.add_column('channels', sa.Column('handle', sa.String(length=128), nullable=True))
    op.add_column(
        'channels',
        sa.Column(
            'stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default='{}',
        ),
    )
    op.add_column('scripts', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.add_column(
        'scripts',
        sa.Column('language', sa.String(length=16), nullable=False, server_default='en'),
    )
    op.add_column(
        'scripts',
        sa.Column(
            'platform', sa.String(length=32), nullable=False, server_default='youtube_long',
        ),
    )
    op.add_column(
        'scripts',
        sa.Column(
            'b_roll_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default='[]',
        ),
    )
    op.add_column(
        'scripts',
        sa.Column(
            'power_word_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            server_default='[]',
        ),
    )
    op.add_column('scripts', sa.Column('duration_estimate_seconds', sa.Float(), nullable=True))
    op.add_column('scripts', sa.Column('rating_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scripts', sa.Column('final_text', sa.Text(), nullable=True))
    op.add_column('transcripts', sa.Column('language_detected', sa.String(length=16), nullable=True))
    op.add_column(
        'transcripts', sa.Column('raw_text', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'transcripts', sa.Column('clean_text', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'voice_profiles',
        sa.Column('source', sa.String(length=16), nullable=False, server_default='initial'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'source')
    op.drop_column('transcripts', 'clean_text')
    op.drop_column('transcripts', 'raw_text')
    op.drop_column('transcripts', 'language_detected')
    op.drop_column('scripts', 'final_text')
    op.drop_column('scripts', 'rating_detail')
    op.drop_column('scripts', 'duration_estimate_seconds')
    op.drop_column('scripts', 'power_word_spans')
    op.drop_column('scripts', 'b_roll_suggestions')
    op.drop_column('scripts', 'platform')
    op.drop_column('scripts', 'language')
    op.drop_column('scripts', 'topic_id')
    op.drop_column('channels', 'stats')
    op.drop_column('channels', 'handle')
    op.drop_index(op.f('ix_feature_flags_name'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
