"""prompt templates and invocation log

Revision ID: 2b3344dadc81
Revises: 8d633752851c
Create Date: 2026-07-19 15:54:33.370773

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2b3344dadc81'
down_revision: str | None = '8d633752851c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_invocations',
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('rendered_prompt', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_invocations_feature'), 'prompt_invocations', ['feature'], unique=False)
    op.create_index(op.f('ix_prompt_invocations_reference_id'), 'prompt_invocations', ['reference_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature', 'version', name='uq_prompt_templates_feature_version')
    )
    op.create_index(op.f('ix_prompt_templates_feature'), 'prompt_templates', ['feature'], unique=False)
    op.create_index('uq_prompt_templates_feature_active', 'prompt_templates', ['feature'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_prompt_templates_feature_active', table_name='prompt_templates', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_prompt_templates_feature'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_prompt_invocations_reference_id'), table_name='prompt_invocations')
    op.drop_index(op.f('ix_prompt_invocations_feature'), table_name='prompt_invocations')
    op.drop_table('prompt_invocations')
    # ### end Alembic commands ###
