"""channel niche assignments

Revision ID: 5ed3c7969088
Revises: 45683fb2aa2f
Create Date: 2026-07-17 02:53:04.849514

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5ed3c7969088'
down_revision: str | None = '45683fb2aa2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_niche_assignments',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('niche', sa.String(length=64), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_niche_assignments_channel_id'), 'channel_niche_assignments', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channel_niche_assignments_niche'), 'channel_niche_assignments', ['niche'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_niche_assignments_niche'), table_name='channel_niche_assignments')
    op.drop_index(op.f('ix_channel_niche_assignments_channel_id'), table_name='channel_niche_assignments')
    op.drop_table('channel_niche_assignments')
    # ### end Alembic commands ###
