"""voice DNA pipeline, thumbnails, script outcomes, provenance, events log

Revision ID: 844e11f1dd7b
Revises: 24122350e4a3
Create Date: 2026-07-18 16:08:52.394223

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '844e11f1dd7b'
down_revision: str | None = '24122350e4a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('events',
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excerpt_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_prompt_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'version', name='uq_voice_profiles_channel_version')
    )
    op.create_index(op.f('ix_voice_profiles_channel_id'), 'voice_profiles', ['channel_id'], unique=False)
    op.create_table('videos',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('external_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_for_dna', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_external_video_id'), 'videos', ['external_video_id'], unique=False)
    op.create_table('script_outcomes',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('external_video_id', sa.String(length=32), nullable=False),
    sa.Column('matched_by', sa.String(length=16), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('avg_view_duration', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_outcomes_script_id'), 'script_outcomes', ['script_id'], unique=False)
    op.create_table('thumbnail_briefs',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_briefs_script_id'), 'thumbnail_briefs', ['script_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_video_id'), 'transcripts', ['video_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('segment_type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.add_column('channels', sa.Column('current_voice_profile_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_channels_current_voice_profile_id',
        'channels',
        'voice_profiles',
        ['current_voice_profile_id'],
        ['id'],
    )
    op.drop_column('channels', 'voice_dna')
    op.add_column('scripts', sa.Column('voice_profile_version', sa.Integer(), nullable=True))
    op.add_column('scripts', sa.Column('agent_name', sa.String(length=64), nullable=False))
    op.add_column('scripts', sa.Column('agent_version', sa.String(length=32), nullable=False))
    op.add_column('scripts', sa.Column('prompt_version', sa.String(length=32), nullable=False))
    op.add_column('scripts', sa.Column('model_id', sa.String(length=128), nullable=False))
    op.add_column('scripts', sa.Column('input_tokens', sa.Integer(), nullable=False))
    op.add_column('scripts', sa.Column('output_tokens', sa.Integer(), nullable=False))
    op.add_column('scripts', sa.Column('cost', sa.Float(), nullable=False))
    op.add_column('usage', sa.Column('feature', sa.String(length=32), nullable=False))
    op.add_column('usage', sa.Column('tokens', sa.Integer(), nullable=False))
    op.add_column('usage', sa.Column('cost', sa.Float(), nullable=False))
    op.drop_constraint(op.f('uq_usage_user_day'), 'usage', type_='unique')
    op.create_unique_constraint('uq_usage_user_day_feature', 'usage', ['user_id', 'day', 'feature'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usage_user_day_feature', 'usage', type_='unique')
    op.create_unique_constraint(op.f('uq_usage_user_day'), 'usage', ['user_id', 'day'], postgresql_nulls_not_distinct=False)
    op.drop_column('usage', 'cost')
    op.drop_column('usage', 'tokens')
    op.drop_column('usage', 'feature')
    op.drop_column('scripts', 'cost')
    op.drop_column('scripts', 'output_tokens')
    op.drop_column('scripts', 'input_tokens')
    op.drop_column('scripts', 'model_id')
    op.drop_column('scripts', 'prompt_version')
    op.drop_column('scripts', 'agent_version')
    op.drop_column('scripts', 'agent_name')
    op.drop_column('scripts', 'voice_profile_version')
    op.add_column('channels', sa.Column('voice_dna', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('fk_channels_current_voice_profile_id', 'channels', type_='foreignkey')
    op.drop_column('channels', 'current_voice_profile_id')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_transcripts_video_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_thumbnail_briefs_script_id'), table_name='thumbnail_briefs')
    op.drop_table('thumbnail_briefs')
    op.drop_index(op.f('ix_script_outcomes_script_id'), table_name='script_outcomes')
    op.drop_table('script_outcomes')
    op.drop_index(op.f('ix_videos_external_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_voice_profiles_channel_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
