"""billing usage summary, script measurement, idempotency constraints

Revision ID: 8d633752851c
Revises: 2af37296507c
Create Date: 2026-07-18 22:57:16.043585

"""
from collections.abc import Sequence

from alembic import op

revision: str = '8d633752851c'
down_revision: str | None = '2af37296507c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_script_outcomes_script_id', 'script_outcomes', ['script_id'])
    op.create_unique_constraint(
        'uq_videos_channel_external_id', 'videos', ['channel_id', 'external_video_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_videos_channel_external_id', 'videos', type_='unique')
    op.drop_constraint('uq_script_outcomes_script_id', 'script_outcomes', type_='unique')
    # ### end Alembic commands ###
